Garden/Garden/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'Garden'
urlpatterns = [
    path('', views.index, name='index'),
    path('registerAcount/', views.registerAcount, name='registerAcount'),
    path('loginAcount/',views.loginAcount, name='loginAcount')
]

Garden/mysite/urls.py
from django.contrib import admin
from django.urls import include,path
from django.views.generic.base import TemplateView

urlpatterns = [
    path('garden',include('Garden.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='registration/home.html'), name='home'),
    path('admin/', admin.site.urls),
]

Garden/Garden/models.py
from django.db import models
from django.utils import timezone

class Registration(models.Model):
    Email = models.CharField(max_length=20)
    subject = models.CharField(max_length=20,null=True)
    text = models.CharField(max_length=400)

    def __str__(self):
        return self.Email

class UserLists(models.Model):
    name = models.CharField(max_length=20)
    password = models.CharField(max_length=20)
    Email = models.EmailField(max_length=20)

    def __str__(self):
        return self.name

Garden/Garden/forms.py
from django import forms

class SentMaill(forms.Form):
    Email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'contact-email','placeholder':'Email','type':'text'}))
    subject = forms.CharField(widget=forms.TextInput(attrs={'class':'contact-subject','placeholder':'Subject'}),required=False)
    text = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control','placeholder':'Message'}))

class register(forms.Form):
    text = forms.CharField(widget=forms.TextInput(attrs={'type':'text','placeholder':'name'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'type':'password','placeholder':'password'}))
    Email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder':'email address','type':'text'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'type':'text','placeholder':'name'}))

class login(forms.Form):
    text = forms.CharField(widget=forms.TextInput(attrs={'type':'text','placeholder':'name'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'type':'password','placeholder':'password'}))

Garden/Garden/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from .models import Registration, UserLists
from .forms import SentMaill, register, login
# Create your views here.



def index(request):
    forms = SentMaill()
    if request.method == 'POST':
        forms = SentMaill(request.POST)

        if forms.is_valid():
            new_message = Registration(Email=request.POST['Email'],subject=request.POST['subject'],text=request.POST['text'])
            new_message.save()
            return redirect('Garden:index')
    else:
        forms = SentMaill()

    context = {"form":forms}
    return render(request,'Garden/index.html',context)

def registerAcount(request):
    forms = register()
    if request.method == 'POST':
        forms = register(request.POST)

        if forms.is_valid():
            user = User.objects.create_user(request.POST['text'],request.POST['Email'],request.POST['password'])
            user.save()
            return redirect('Garden:index')
    else:
        forms = register()

    context = {"form":forms}
    return render(request,'Garden/registerAcount.html',context)

def loginAcount(request):
    forms = login()
    if request.method == 'POST':
        forms = login(request.POST)

        if forms.is_valid():
            username = request.POST['text']
            password = request.POST['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                #return redirect('Garden:index')
            #else:
                #return redirect('Garden:loginAcount')
    else:
        forms = login()

    context = {"form":forms}
    return render(request,'Garden/login.html',context)

Garden/Garden/templates/Garden/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>GARDEN</title>
    <link rel="shortcut icon" href="{% static 'Garden/images/5.png' %}">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Dosis:300,400,500,600,700">
    <link rel="stylesheet" href="{% static 'Garden/stylesheet.css' %}">
    <link rel="stylesheet" href="{% static 'Garden/responsive.css' %}">
    <link rel="stylesheet" href="{% static 'Garden/css-slider.css' %}">
</head>
<body>
    <div class="container">
        <div class="header-title">
          <a class="header-logo" href="#home">GARDEN</a>
        </div>
        <div class="header-menu">
          <ul class="header-menu-right">
            <li>
              <a href="#languages">HOME</a>
            </li>
            <li>
              <a href="#features">ABOUT</a>
            </li>
            <li>
              <a href="{% url 'Garden:loginAcount' %}">MyPage</a>
            </li>
            <li>
              <a href="#columns">REACTION</a>
            </li>
            <li>
              <a href="#contact">お問い合わせ</a>
            </li>
          </ul>
        </div>
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

Garden/Garden/templates/Garden/index.html
{% extends 'Garden/base.html' %}
{% load static %}
{% block content %}
<!-- Top content -->
    <div id="home" class="top-section">
      <div class="inner-bg">
        <div class="container">
          <div class="top-description">
            <h2>GARDENは自分と世界をつなぐ君だけの箱庭</h2>
            <p>下のボタンを押してどうやって投稿するのか見てみよう！</p>
          </div>
          <div class="top-detail">
            <a class="btn btn-top-white btn-lg" id="read-more">投稿する！</a>
          </div>
        </div>
      </div>
    </div>

    <!-- Languages -->
    <div id="languages" class="languages-section">
      <div class="container">
        <div class="section-title">
          <h3>ランキング</h3>
        </div>
        <div class="languages-box-wrapper">
          <div class="languages-box">
            <div class="icon">
              <img src="{% static 'Garden/images/1.png' %}" alt="My image">
            </div>
            <h4>English</h4>
            <p>もじもじもじも<br>もじもじもじもじもじ</p>
          </div>
          <div class="languages-box">
            <div class="icon">
              <img src="{% static 'Garden/images/2.png' %}" alt="My image">
            </div>
            <h4>Korean</h4>
            <p>ぶんぶんぶんぶんぶんぶんぶん<br>ぶんぶんぶんぶんぶんぶんぶんぶん</p>
          </div>
          <div class="languages-box">
            <div class="icon">
              <img src="{% static 'Garden/images/3.png' %}" alt="My image">
            </div>
            <h4>Russian</h4>
            <p>ありがとうありがとうありがとう<br>ありがとうありがとうありがとう</p>
          </div>
          <div class="languages-box">
            <div class="icon">
              <img src="https://s3-ap-northeast-1.amazonaws.com/progate/shared/images/lesson/html/practice/lang_icons/git.png">
            </div>
            <h4>Japanese</h4>
            <p>いただきますいただきます、<br>いただきますいただきます</p>
          </div>
        </div>
      </div>
    </div>

    <!-- Features -->
    <div id="features" class="features-section">
      <div class="features-section-top gray-section">
        <div class="container">
          <div class="section-title">
            <h3>GARDENって何？</h3>
          </div>
          <img class="features-image" src="{% static 'Garden/images/5.png' %}">
        </div>
      </div>
      <div class="features-section-bottom">
        <div class="container">
          <div class="features-box">
            <h5>① aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</h5>
            aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa。
          </div>
          <div class="features-box">
            <h5>② aaaaaaaaaaaaaaaaaaaaaaaaaaaa</h5>
            aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa。
          </div>
          <div class="features-box">
            <h5>③ aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</h5>
            aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
            aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
          </div>
          <div class="features-box">
            <h5>④ aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</h5>
            aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa。
          </div>
        </div>
      </div>
    </div>

    <!-- Message -->
    <div class="message-section">
      <div class="message-section-inner">
        <div class="container">
          <h4>ソンムンだけの交流場があってもいいんじゃない？
            <br>- GARDEN
          </h4>
        </div>
      </div>


    </div>


    <!-- Contact -->
    <div id="contact" class="contact-section">
      <div class="contact-section-inner">
        <div class="container">
          <div class="section-title">
            <h3>お問い合わせ</h3>
          </div>
          <div class="contact-form">
            <h4>メッセージを送る</h4>
            <form method="post" action="{% url 'Garden:index' %}">
              {% csrf_token %}
              {{ form.Email }}
              {{ form.subject }}
              {{ form.text }}
              <!--<input type="text" name="email" placeholder="Email" class="contact-email">
              <input type="text" name="subject" placeholder="Subject" class="contact-subject">
              <textarea name="message" class="form-control" placeholder="Message"></textarea>-->
              <button type="submit" class="btn btn-contact">Submit</button>
            </form>
          </div>
          <div class="contact-about">
            <h4>About Us</h4>
            <p>サンプルサンプルサンプルサンプルサンプルサンプルサンプル
              サンプルサンプルサンプルサンプルサンプルサンプルサンプル
              サンプルサンプルサンプルサンプルサンプルサンプルサンプル
              サンプルサンプルサンプルサンプルサンプルサンプルサンプル
              サンプルサンプルサンプル
            </p>
            <h4>Address</h4>
            <p><i class="fa fa-map-marker"></i>korea asan sunmoon univ</p>
            <p><i class="fa fa-phone"></i>Phone: 00-0000-0000</p>
          </div>
        </div>
      </div>
    </div>

    <!-- Social -->
    <div class="social-section">
      <div class="container">
        <div class="section-title">
          <h3>GARDENの公式アカウントをチェック!</h3>
        </div>
        <div class="follow-us">
          <a href="公式アカウントのURL" class="social-icon" target='_blank'>
            <i class="fa fa-facebook"></i>
          </a>
          <a href="公式アカウントのURL" class="social-icon" target='_blank'>
            <i class="fa fa-twitter"></i>
          </a>
        </div>
      </div>
    </div>
    <footer>
      <div class="container">
        <div class="copyright">©2018-
        </div>
      </div>
    </footer>
{% endblock %}

Garden/Garden/templates/Garden/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>GARDEN/registerAcount</title>
    <link rel="shortcut icon" href="{% static 'Garden/images/5.png' %}">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Dosis:300,400,500,600,700">
    <link rel="stylesheet" href="{% static 'Garden/login.css' %}">
    <link rel="stylesheet" href="{% static 'Garden/login.js' %}">
</head>
<div class="login-page">
  <div class="form">
    <form method="post" class="login-form" action="{% url 'Garden:index' %}">
      {% csrf_token %}
      {{ form.text }}
      {{ form.password }}
      <button>login</button>
      <p class="message">Not registered? <a href="{% url 'Garden:registerAcount' %}">Create an account</a></p>
    </form>
  </div>
</div>
</html>

Garden/Garden/templates/Garden/registerAcount.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>GARDEN/registerAcount</title>
    <link rel="shortcut icon" href="{% static 'Garden/images/5.png' %}">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Dosis:300,400,500,600,700">
    <link rel="stylesheet" href="{% static 'Garden/login.css' %}">
    <link rel="stylesheet" href="{% static 'Garden/login.js' %}">
</head>
<div class="login-page">
  <div class="form">
    <form method="post" class="login-form" action="{% url 'Garden:registerAcount' %}">
      {% csrf_token %}
      {{ form.text }}
      {{ form.password }}
      {{ form.Email }}
      {{ form.last_name }}
      <button>create</button>
      <p class="message">Already registered? <a href="{% url 'Garden:loginAcount' %}">Sign In</a></p>
    </form>
  </div>
</div>
</html>